# docker compose edition 
version: "3.8"

services:
  #  node 1
  cubejs:
    #  Image name 
    image: cubejs/cube:latest
    #  Container name 
    container_name: cubejs-server
    # docker Automatically restart the container after restart
    restart: always
    # 跨多个Docker-compose配置文件，services在一个网桥
    networks:
      - dev-network
    #  Current container hostname
    hostname: cubejs-server
    #  port   The host machine : Containers 
    ports:
      - 14000:4000
    #  environment variable 
    environment:
      CUBEJS_DEV_MODE: true
    volumes:
      - ./cube/conf:/cube/conf

networks:
  dev-network:
    external: true